### ISSUE TITLE
NoSuchFileException: tokenizer.bin

### ISSUE THREAD

**Issue by msche** [mukel/llama2.java#3]
I just checked out your project and downloaded the stories15M (` wget https://huggingface.co/karpathy/tinyllamas/resolve/main/stories15M.bin`). I compiled the llama java class

```
javac --enable-preview -source 20 --add-modules=jdk.incubator.vector Llama2.java
warning: using incubating module(s): jdk.incubator.vector
Note: Llama2.java uses preview features of Java SE 20.
Note: Recompile with -Xlint:preview for details.
1 warning
```

When I execute the java class I get the following exception:

```
java --enable-preview --add-modules=jdk.incubator.vector Llama2 stories15M.bin  
WARNING: Using incubator modules: jdk.incubator.vector
Config{dim=288, hidden_dim=768, n_layers=6, n_heads=6, n_kv_heads=6, vocab_size=32000, seq_len=256, shared_weights=true, head_size=48}
Exception in thread "main" java.nio.file.NoSuchFileException: tokenizer.bin
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:224)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:308)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:367)
        at Tokenizer.<init>(Llama2.java:208)
        at Llama2.main(Llama2.java:1006)
```

I'm using openjdk version 20:

```
openjdk version "20.0.2" 2023-07-18
OpenJDK Runtime Environment (build 20.0.2+9-78)
OpenJDK 64-Bit Server VM (build 20.0.2+9-78, mixed mode, sharing)
```

**Comment by mukel** [comment]
Hi, the [tokenizer.bin](https://github.com/karpathy/llama2.c/raw/master/tokenizer.bin) must be in the current working directory. It is briefly mentioned in the [README#Build](https://github.com/mukel/llama2.java#build) section.

**Comment by msche** [comment]
Thanks, put it there and got it working indeed
